@ stdcall BTCpuGetBopCode()
@ stdcall BTCpuGetContext(long long ptr ptr)
@ stdcall BTCpuProcessInit()
@ stdcall BTCpuThreadInit()
@ stdcall BTCpuResetToConsistentState(ptr)
@ stdcall BTCpuSetContext(long long ptr ptr)
@ stdcall -norelay BTCpuSimulate()
@ stdcall BTCpuTurboThunkControl(long)
#@ stub TurboDispatchJumpAddressEnd
#@ stub TurboDispatchJumpAddressStart
@ stdcall BTCpuNotifyUnmapViewOfSection(ptr long)
@ stdcall BTCpuNotifyMemoryFree(ptr long long)
@ stdcall BTCpuNotifyMemoryProtect(ptr long long)
@ stdcall BTCpuFlushInstructionCache2(ptr long)
@ stdcall __wine_get_unix_opcode()
